services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    ports:
      - "8090:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
