# Generated by Django 3.2.21 on 2023-09-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioItem',
            new_name='PortofolioItem',
        ),
    ]
