# Generated by Django 3.2.21 on 2023-09-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0003_alter_portofolioitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolioitem',
            name='image',
            field=models.ImageField(upload_to='static/portfolio/'),
        ),
    ]
